joint_limits:
  arm_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 0.62831853
  torso_lower_neck_tilt_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.1
  torso_upper_neck_tilt_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.1
  lookat_x_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 0.2
  arm_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 0.62831853
  arm_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 0.62831853
  torso_pan_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 0.1
  arm_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 0.62831853
  lookat_lin_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 0.2
  lookat_y_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 0.2
  arm_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 0.62831853
  lookat_z_joint:
    has_velocity_limits: true
    max_velocity: 1
    has_acceleration_limits: true
    max_acceleration: 0.2
  ur_connector_joint:
    has_velocity_limits: true
    max_velocity: 1.9634
    has_acceleration_limits: true
    max_acceleration: 0.39268
  arm_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.14159265
    has_acceleration_limits: true
    max_acceleration: 0.62831853